### ISSUE TITLE
Reiterate Example Notebooks

### ISSUE THREAD

**Issue by MoritzWillmann** [sQUlearn/squlearn#11]
This includes:
- checking for necessity
- checking if runs
- adding more explanations

For
- [x] `executor`
- [x] `feature_maps`
- [x] `kernel`
- [x] `qnn`
- [x] `tutorials`

**Comment by rothma** [comment]
This is done, isn't it?

**Comment by JanSchnabel** [comment]
> This is done, isn't it?

For Executor and feature maps, there is a tick missing

**Comment by David-Kreplin** [comment]
I finished the remaining examples and close now this issue.
