### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by MoritzWillmann** [sQUlearn/squlearn#12]
We need a unified documentation and documentation framework.

#### User Guides
- [x] Executor
- [x] Operators for Expectation Values
- [x] Quantum Feature Maps
- [x] Quantum Kernel Methods
- [ ] #115

#### Overview Pages
(context and a bit background, in class docstrings)
- [x] Executor
- Classifiers
    - [x] QSVC
    - [x] QGPC
    - [x] QNNClassifier
- Regressors
    - [x] QSVR
    - [x] QKRR
    - [x] QGPR
    - [x] QNNRegressor

#### Building Block Documentation
(minimal example + visualisation)
- [x] Operators
- [x] Feature Maps

#### Minimal docstrings
(just short description and parameters)
- for everything that is not listed in Overview Pages

#### Examples
- [ ] #116
- [x] Mnist Classification with PQK
- [ ] #118
- [ ] #117

**Comment by MoritzWillmann** [comment]
Docstring order:
- Short description (one sentence)
- Long description
- Parameters
- See Also
- References
- Example
- Methods

**Comment by MoritzWillmann** [comment]
Nice 🎉 Docs for HL-Routines are done

**Comment by rothma** [comment]
The layout of the documentation is a bit weird:

- we need a landing page
- API Reference is not an illustrative name and it subsumes many things that are not really connected ->
- [ ] New Hirarchy top level -> lower level: QML Regressors, QML Classifiers, Circuit Design -> Operators, Feature Maps -> Tools for Feature maps, (?unclear?) Low-Level -> Base Classes, Quantum Kernel, QNN
- [ ] Top Level: Tutorials -> Executor, Projected Quanum Kernel, Operators for expectation values, Quantum Feature Maps.

**Comment by MoritzWillmann** [comment]
I think we can close this Issue and transform all open points to separate issues
