### ISSUE TITLE
Testjobs and pipeline for testing

### ISSUE THREAD

**Issue by MoritzWillmann** [sQUlearn/squlearn#13]
We Require some basic functionality tests for all our modules.

**Comment by MoritzWillmann** [comment]
PR #74 will add tests for `QNNRegressor` and `QNNClassifier`. They can be used as templates on how to formulate your tests. Please try to Cover as much of the basic functionality of the modules without implementing a full unit-test setup. This is for other times.

**Comment by rothma** [comment]
Add tests to pipeline?
