### ISSUE TITLE
Rename Feature maps -> Encoding Circuits

### ISSUE THREAD

**Issue by rothma** [sQUlearn/squlearn#132]
Because it's the right thing to do

**Comment by rothma** [comment]
Proposals:

- **encoding_circuits**
- data_encoding_circuits. Nennen: dec
- ansatz

**Comment by rothma** [comment]
Final discussion with david and then go to work

**Comment by rothma** [comment]
@David-Kreplin brought up a potential issue with non-x-dependent circuits --> pqc?

Also, let's change the name of the implemented feature maps to something meaningful (e.g. qek, param_z, highdim?)

**Comment by JanSchnabel** [comment]
But the same would hold for only-x-depending circuits. Okay, then x can be viewed as parameter and therefore pqc would be fine. What about something even more general like SqulearnCircuits as analogue to Qiskit's QuantumCircuit?

**Comment by MoritzWillmann** [comment]
> @David-Kreplin brought up a potential issue with non-x-dependent circuits --> pqc?

Does this UC exist? I'd be fine with pqc aswell, though.

> But the same would hold for only-x-depending circuits. Okay, then x can be viewed as parameter and therefore pqc would be fine. What about something even more general like SqulearnCircuits as analogue to Qiskit's QuantumCircuit?

I'm not sure if we should come up with something that isn't really meaningful. Just calling it Circuit or QuantumCircuit might work though.

**Comment by rothma** [comment]
Since data encoding circuits will be the default case, I would prefer to keep it as a name. My suggestion would be to rename the `feature_maps_implemented` to data encoding circuits and maybe rename the parent folder to `circuits` or something along these lines.

**Comment by David-Kreplin** [comment]
Closed with PR #159
