### ISSUE TITLE
example_executor does not run

### ISSUE THREAD

**Issue by rothma** [sQUlearn/squlearn#164]
- Some missing imports, can probably be fixed quickly.
- Additionally, there is a bunch of commented code. Not sure if this is on purpose. Can you have a look @David-Kreplin ?
![grafik](https://github.com/sQUlearn/squlearn/assets/23644014/39744542-7030-4ce9-a019-b668c5946439)

**Comment by David-Kreplin** [comment]
Will be fixed with my update on the mitigation user guide.
