### ISSUE TITLE
`qiskit_machine_learning.kernels.QuantumKernel` is deprecated as of `0.7.0`

### ISSUE THREAD

**Issue by MoritzWillmann** [sQUlearn/squlearn#198]
We need to find an alternative. Sadly the implemenation of `qiskit_machine_learning.kernels.FidelityQuantumKernel` (which is also used by `qiskit_machine_learning.kernels.TrainableFidelityQuantumKernel` internally) is very slow and thus not an alternative at the moment.

**Comment by dtchang** [comment]
This needs to be fixed ASAP. The existing import breaks all examples.

**Comment by MoritzWillmann** [comment]
Hey @dtchang, thanks for checking out the examples <3 We're looking for a solution. Until we find one, you can still use sQUlearn with the recommended dependencies (i.e. qiskit-machine-learning<0.7.0). Also any input is appreciated!

**Comment by dtchang** [comment]
Qiskit-ml now supports FidelitQuantumKernel and FidelityStatevectorKernel, as well as two corresponding trainable versions, with the latter providing the same performance as the deprecated QuantumKernel. I suppose sQUlearn FidelityKernel needs to be revised accordingly.

**Comment by MoritzWillmann** [comment]
As I mentioned above, `FidelityQuantumKernel`is sadly very inefficient and thus not a real option atm. Thanks for pointing out `FidelityStatevectorKernel` though. I'll have a look if that could be an suitable option.

**Comment by dtchang** [comment]
Please release the updates ASAP. Thanks!

**Comment by MoritzWillmann** [comment]
Solved and as of now available in develop branch and with next release
