### ISSUE TITLE
Meaurements in QCNN encoding circuits are not working with statevector 

### ISSUE THREAD

**Issue by David-Kreplin** [sQUlearn/squlearn#226]
Circuits that are created by the QCNNEncodingCircuit class with pooling layers including in-circuit measurements (e.g. .pooling(measurement=True)) are not compatible with current sQUlearn implementation. 

Please throw an error for such cases.

We have to figure out, how that can be implemented with the Qiskit primitives and check the gradients.

**Comment by David-Kreplin** [comment]
Problem exists only for statevector simulators. Here in-circuit measurement is not possible in general.

**Comment by MoritzWillmann** [comment]
Does this issue go beyond the scope of PR #227 ? If no I suggest closing this issue and using the PR thread for comments, discussions...
