### ISSUE TITLE
Add simple VQE tools

### ISSUE THREAD

**Issue by David-Kreplin** [sQUlearn/squlearn#40]
Interesting add-ons such that the QNN engine can be used as a simple VQE tool:

 - VQE loss function (return output of the QNN)
 - Hamilton variational ansatz feature map (create a feature map from a given operator)
 - Typical VQE feature maps (SU2 Efficient, UCCSD, ...)
 - Better tools for splitting circuits for different pauli operators (more work)

**Comment by rothma** [comment]
Do we still consider adding this?
