### ISSUE TITLE
High-level methods need to be able to set feature map hyperparameters (e.g. num_qubits, num_layers)

### ISSUE THREAD

**Issue by rothma** [sQUlearn/squlearn#62]
- Problem could e.g. arise in ProjectedKernel which already create a circuit when initialized (which can happen before it is fed into a high-level ML method)

**Comment by rothma** [comment]
Same for projected kernel length-scale parameter?

**Comment by MoritzWillmann** [comment]
Implemented in #90 #99 and #107
